services:
  ebank-discovery-service:
    build: ./discovery-service
    container_name: ebank-discovery-service
    ports:
      - "8761:8761"
    expose:
      - '8761'
    healthcheck: #tester si le microservice est toujours démarré
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
  ebank-config-service:
    build: ./config-service
    container_name: ebank-config-service
    ports:
      - "1111:1111"
    expose:
      - '1111'
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1111/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      ebank-discovery-service:
        condition: service_healthy
  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "8082:8082"
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://ebank-config-service:1111
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      ebank-config-service:
        condition: service_healthy
  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8083:8083"
    expose:
      - '8083'
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://ebank-config-service:1111
    depends_on:
      customer-service:
        condition: service_healthy
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8888:8888"
    expose:
      - '8888'
    healthcheck: #tester si le microservice est toujours démarré
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://ebank-config-service:1111
    depends_on:
      ebank-discovery-service:
        condition: service_healthy
  angular-cust-app:
    build: ./angular-front-end
    container_name: angular-cust-app
    ports:
      - "80:80"
    expose:
      - '80'
    depends_on:
      gateway-service:
        condition: service_healthy